services:
  postgres:
    image: postgres:17.5-alpine
    container_name: pita_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-pita}
      POSTGRES_USER: ${DB_USER:-pita_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pita_pass}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      # データ永続化
      - postgres_data:/var/lib/postgresql/data
      # 初期化SQLを実行（ファイル名順で実行される）
      - ./database/init:/docker-entrypoint-initdb.d:ro
      # PostgreSQL設定
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - pita_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-pita_user} -d ${DB_NAME:-pita}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  air:
    build:
      context: ./backend
      dockerfile: ./Dockerfile/air/dockerfile.yml 
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app
    networks:
      - pita_network

volumes:
  postgres_data:
    driver: local

networks:
  pita_network:
    driver: bridge
