version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-portfolio}
      POSTGRES_USER: ${DB_USER:-portfolio_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-portfolio_pass}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      # データ永続化
      - postgres_data:/var/lib/postgresql/data
      # 初期化SQLを実行（ファイル名順で実行される）
      - ./database/init:/docker-entrypoint-initdb.d:ro
      # PostgreSQL設定（オプション）
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - portfolio_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-portfolio_user} -d ${DB_NAME:-portfolio}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 開発用のadminer（データベース管理ツール）- オプション
  adminer:
    image: adminer:latest
    container_name: portfolio_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - portfolio_network
    profiles:
      - dev # docker-compose --profile dev up で起動

volumes:
  postgres_data:
    driver: local

networks:
  portfolio_network:
    driver: bridge
